media:
  input: src/assets/images
  output: /assets/images
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    filename: "{primary}.md"
    view:
      fields: [ title, date ]
      primary: title
      sort: [ title, date ]
      default:
        sort: date
        order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description (Between 150-160 Characters Including Spaces)
        type: string
        options:
          minlength: 150
          maxlength: 160
      - name: date
        label: Date
        type: date
        default: false
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss
      - name: keywords
        label: Keywords (Multiple Allowed)
        type: string
        list:
          collapsible: false
      - name: tags
        label: Tags (Multiple Allowed)
        type: select
        options:
          creatable: true
          multiple: true
          values: [Machining, Fabrication, Inspection, Design, Welding, Turning, Milling]
      - name: categories
        label: Categories (Single Only)
        type: select
        options:
          creatable: false
          multiple: false
          values: [Machining, Fabrication, Inspection, Design]
      - name: image
        label: Image (Single Only)
        type: image
      - name: imageAlt
        label: Image Description
        type: string
      - name: body
        label: Main Post Content
        type: rich-text

  - name: vacancies
    label: Vacancies
    type: collection
    path: src/content/vacancies
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ title ]
      default:
        sort: title
        order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Main Content
        type: rich-text

  - name: fab-blocks
    label: Fabrication Page Blocks
    type: collection
    path: src/content/fab-blocks
    filename: "{primary}.md"
    view:
      fields: [ title ]
      primary: title
      sort: [ title ]
      default:
        sort: title
        order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: icon
        label: Icon
        type: string
      - name: body
        label: Main Content
        type: rich-text

  - name: fab-links
    label: Fabrication Page Links
    type: collection
    path: src/content/fab-links
    filename: "{primary}.md"
    view:
      fields: [ title ]
      primary: title
      sort: [ title ]
      default:
        sort: title
        order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: image
        label: Image (Single Only, Company Logo)
        type: image
      - name: alt
        label: Image Description
        type: string
      - name: url
        label: Url Of Company i.e. (https://lorch.com)
        type: string

  - name: fab-images
    label: Fabrication Page Images
    type: collection
    path: src/content/fab-images
    filename: "{primary}.md"
    view:
      fields: [ title ]
      primary: title
      sort: [ title ]
      default:
        sort: title
        order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: image
        label: Image (Single Only)
        type: image
      - name: imageAlt
        label: Image Description
        type: string

  - name: machine-blocks
    label: Machining Page Blocks
    type: collection
    path: src/content/machine-blocks
    filename: "{primary}.md"
    view:
      fields: [ title ]
      primary: title
      sort: [ title ]
      default:
        sort: title
        order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: icon
        label: Icon
        type: string
      - name: body
        label: Main Content
        type: rich-text

  - name: machine-links
    label: Machining Page Links
    type: collection
    path: src/content/machine-links
    filename: "{primary}.md"
    view:
      fields: [ title ]
      primary: title
      sort: [ title ]
      default:
        sort: title
        order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: image
        label: Image (Single Only)
        type: image
      - name: alt
        label: Image Description
        type: string
      - name: url
        label: Url Of Company i.e. (https://lorch.com)
        type: string

  - name: machine-images
    label: Machining Page Images
    type: collection
    path: src/content/machine-images
    filename: "{primary}.md"
    view:
      fields: [ title ]
      primary: title
      sort: [ title ]
      default:
        sort: title
        order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: image
        label: Image (Single Only)
        type: image
      - name: imageAlt
        label: Image Description
        type: string

  - name: pages
    label: Pages
    type: collection
    path: src/content/pages
    filename: '{primary}.md'
    view:
      fields: [ title ]
      primary: title
      sort: [ title ]
      default:
        sort: title
        order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description (Between 150-160 Characters Including Spaces)
        type: string
        options:
          minlength: 150
          maxlength: 160
      - name: keywords
        label: Keywords (Multiple Allowed)
        type: string
        list:
          collapsible: false
      - name: permalink
        label: Permalink (Don't Edit)
        type: string
        default: '/{fields.title | slugify}/'
        editable: false
      - name: layout
        label: Layout
        type: select
        options:
          values:
            - value: base
              label: Base
            - value: default
              label: Default
            - value: contact
              label: Contact
            - value: fabrication
              label: Fabrication
            - value: machining
              label: Machining
        default: 'base'
      - name: pageType
        label: Page Type
        type: select
        options:
          values:
            - value: contact
              label: Contact
            - value: home
              label: Home
            - value: none
              label: None
        default: 'none'
      - name: keywords
        label: Keywords
        type: string
        list:
          collapsible: false
      - name: bkgdimage
        label: Background Image (Single Only, Choose From Header Images)
        type: image
        options:
          multiple: false
          extensions: [jpg, png]
      - name: body
        label: Page Content
        type: rich-text

