media:
  input: src/assets/images
  output: assets/images
content:
  - name: posts
    label: Posts
    type: collection
    path:: src/content/posts
    fields:
      - name: title
        label: Title
        type: string
      - name: summary
        label: Description
        type: string
      - name: date
        label: Date
        type: datetime
        default: false
        format: YYYY-MM-DDTHH:mm:ssZ
      - name: keywords
        label: Keywords
        type: list
      - name: tags
        label: Tags
        type: list
      - name: categories
        label: Categories
        type: list
      - name: image
        label: Image
        type: image
      - name: imageAlt
        label: Image Alt Text
        type: string
      - name: body
        label: Main Body Text
        type: rich-text

  - name: vacancies
    label: Vacancies
    type: collection
    path:: src/content/vacancies/
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Main Body Text
        type: rich-text

  - name: fab-blocks
    label: Fabrication Page Blocks
    type: collection
    path:: src/content/fab-blocks
    fields:
      - name: title
        label: Title
        type: string
      - name: icon
        label: Icon
        type: string
      - name: body
        label: Main Body Text
        type: rich-text

  - name: fab-links
    label: Fabrication Page Links
    type: collection
    path:: src/content/fab-links
    fields:
      - name: title
        label: Title
        type: string
      - name: image
        label: Image
        type: image
      - name: imageAlt
        label: Image Alt Text
        type: string
      - name: url
        label: Url
        type: string

  - name: fab-images
    label: Fabrication Page Images
    type: collection
    path:: src/content/fab-images
    fields:
      - name: title
        label: Title
        type: string
      - name: image
        label: Image
        type: image
      - name: imageAlt
        label: Image Alt Text
        type: string

  - name: machine-blocks
    label: Machining Page Blocks
    type: collection
    path:: src/content/machine-blocks
    fields:
      - name: title
        label: Title
        type: string
      - name: icon
        label: Icon
        type: string
      - name: body
        label: Main Body Text
        type: rich-text

  - name: machine-links
    label: Machining Page Links
    type: collection
    path:: src/content/machine-links
    fields:
      - name: title
        label: Title
        type: string
      - name: image
        label: Image
        type: image
      - name: imageAlt
        label: Image Alt Text
        type: string
      - name: url
        label: Url
        type: string

  - name: machine-images
    label: Machining Page Images
    type: collection
    path:: src/content/machine-images
    fields:
      - name: title
        label: Title
        type: string
      - name: image
        label: Image
        type: image
      - name: imageAlt
        label: Image Alt Text
        type: string

  - name: pages
    label: Page
    type: collection
    path:: src/content/pages
    fields:
      - name: title
        label: Title
        type: string
      - name: summary
        label: Description
        type: string
      - name: keywords
        label: Keywords
        type: string
        list:
          collapsible: false
      - name: layout
        label: Layout
        type: string
      - name: permalink
        label: Permalink
        type: string
      - name: bkgdimage
        label: Background Image
        type: image
      - name: body
        label: Body
        type: rich-text
