media:
  input: src/assets/images
  output: assets/images
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, date ]
      default:
        sort: order
        order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: date
        label: Date
        type: date
        default: false
        format: YYYY-MM-DDTHH:mm:ssZ
      - name: keywords
        label: Keywords
        type: string
        list:
          collapsible: false
      - name: tags
        label: Tags
        type: select
        options:
          multiple: true
          values: [Machining, Fabrication, Inspection, Design, Welding, Turning, Milling]
      - name: categories
        label: Categories
        type: select
        options:
          multiple: false
          values: [Machining, Fabrication, Inspection, Design]
      - name: image
        label: Image
        type: image
      - name: imageAlt
        label: Image Alt Text
        type: string
      - name: body
        label: Main Body Text
        type: rich-text

  - name: vacancies
    label: Vacancies
    type: collection
    path: src/content/vacancies
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default:
        sort: order
        order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Main Body Text
        type: rich-text

  - name: fab-blocks
    label: Fabrication Page Blocks
    type: collection
    path: src/content/fab-blocks
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default:
        sort: order
        order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: icon
        label: Icon
        type: string
      - name: body
        label: Main Body Text
        type: rich-text

  - name: fab-links
    label: Fabrication Page Links
    type: collection
    path: src/content/fab-links
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default:
        sort: order
        order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: image
        label: Image
        type: image
      - name: alt
        label: Image Alt Text
        type: string
      - name: url
        label: Url
        type: string

  - name: fab-images
    label: Fabrication Page Images
    type: collection
    path: src/content/fab-images
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default:
        sort: order
        order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: image
        label: Image
        type: image
      - name: imageAlt
        label: Image Alt Text
        type: string

  - name: machine-blocks
    label: Machining Page Blocks
    type: collection
    path: src/content/machine-blocks
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default:
        sort: order
        order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: icon
        label: Icon
        type: string
      - name: body
        label: Main Body Text
        type: rich-text

  - name: machine-links
    label: Machining Page Links
    type: collection
    path: src/content/machine-links
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default:
        sort: order
        order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: image
        label: Image
        type: image
      - name: alt
        label: Image Alt Text
        type: string
      - name: url
        label: Url
        type: string

  - name: machine-images
    label: Machining Page Images
    type: collection
    path: src/content/machine-images
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default:
        sort: order
        order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: image
        label: Image
        type: image
      - name: imageAlt
        label: Image Alt Text
        type: string

  - name: pages
    label: Pages
    type: collection
    path: src/content/pages
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default:
        sort: order
        order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
        options:
          minlength: 150
          maxlength: 160
      - name: keywords
        label: Keywords
        type: string
        list:
          collapsible: false
      - name: bkgdimage
        label: Background Image
        type: image
        options:
          multiple: false
          path: header-images
          extensions: [jpg, png]
      - name: body
        label: Body
        type: rich-text
