[build]
  command = "npm run build"
  publish = "_site"

[context.production.environment]
  ELEVENTY_ENV = "production"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
    from = "*"
    to = "/404/"
    status = 404
