[build]
  command = "npm run build"
  publish = "_site"

[context.production.environment]
  ELEVENTY_ENV = "production"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[functions]
  directory = "netlify/functions"

[[redirects]]
    from = "*"
    to = "/404/"
    status = 404

[[redirects]]
  from = "/auth"
  to = "/.netlify/functions/auth"
  status = 200