[build]
  command = "npm run build"
  publish = "_site"

[context.production.environment]
  ELEVENTY_ENV = "production"

[[headers]]
    for = "/*"
    [headers.values]
      Report-To = '''{
        "group":"default",
        "max_age":31536000,
        "endpoints":[{"url":"https://fwfrost-engineers.co.uk/a/d/g"}],
        "include_subdomains":true
      }'''

      NEL = '''{
        "report_to":"default",
        "max_age":31536000,
        "include_subdomains":true
      }'''

      Cache-Control = '''
      max-age=300,
      must-revalidate'''
      Content-Security-Policy = "default-src 'self' 'unsafe-inline'; connect-src 'self' 'unsafe-inline' https://plausible.io/api/event; font-src 'self' fonts.gstatic.com; frame-src 'self' https://platform.twitter.com https://www.youtube.com/ https://vimeo.com; img-src 'self' 'unsafe-inline' data: *.cloudfront.net https://www.google.co.uk; media-src 'self' https://www.youtube.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval' https://plausible.io/js/script.js https://cdn.jsdelivr.net https://platform.twitter.com https://unpkg.com; script-src-elem 'self' 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval' https://plausible.io/js/script.js https://cdn.jsdelivr.net https://platform.twitter.com  https://unpkg.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net https://unpkg.com; frame-ancestors 'self'; form-action 'self'"
      Permissions-Policy = "geolocation=(), midi=(), sync-xhr=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), fullscreen=(), payment=(), publickey-credentials-get=()"
      Referrer-Policy= "strict-origin-when-cross-origin"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "SAMEORIGIN"

[[redirects]]
    from = "*"
    to = "/404/"
    status = 404
