export default {
  env: process.env.ELEVENTY_ENV,
  title: 'F W Frost (Engineers) Ltd',
  name: 'F W Frost (Engineers) Ltd',
  description: 'Specialist Equipment & Sub Contract Engineering',
  url: 'https://www.fwfrost-engineers.co.uk',
  localUrl: 'http://localhost:8080',
  language: 'English',
  lang: 'en',
  dir: 'ltr',
  locale: 'en_GB',
  email: 'sales@fwfrost-engineers.co.uk',
  authorName: 'Robert Frost',
  slogan: 'Specialist Equipment & Sub Contract Engineering',
  mobile: '07885170163',
  mobileDisplay: '07885170163',
  telephone: '01603867301',
  telephoneDisplay: '01603 867301',
  telephone1: '01603867354',
  telephoneDisplay1: '01603 867354',
  intPhone: '+441603867301',
  address: 'Frost Industrial Estate',
  village: 'Drayton',
  city: 'Norwich',
  county: 'Norfolk',
  postcode: 'NR8 6AP',
  whatThreewords: 'saints.earplugs.blur',
  latitude: '52.673480',
  longitude: '1.234400',
  twitterSite: 'https://twitter.com/FWFrostLtd',
  twitterCreator: 'FWFrostLtd',
  facebook: 'https://en-gb.facebook.com/pg/FWFROSTLTD/about/',
  linkedIn: 'https://www.linkedin.com/company/f-w-frost-engineers-ltd/',
  opens: '08:00',
  closes: '19:00',
  priceRange: '£100 - £25000',
  metaImage: '/assets/images/social.jpg',
  themeColor: '#ffffff',
  backgroundColor: '#333333'
};

export const pathToSvgLogo = 'src/icon.svg';
